#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ControllerInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ControllerInterface.ControllerInterface_C
// 0x0000 (0x0028 - 0x0028)
class IControllerInterface_C final : public IInterface
{
public:
	void OnUpdateAllSteamInventory();
	void GrantCoinPacks();
	void OnSteamInventoryUpdated(const TArray<struct FSteamItemDetails>& Items);
	void OnGetSteamInventoryItems(TArray<struct FSteamItemDetails>* Items);
	void UpdateWhenResultIsFinished(const struct FSteamInventoryResult& Result);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ControllerInterface_C">();
	}
	static class IControllerInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IControllerInterface_C>();
	}
};
static_assert(alignof(IControllerInterface_C) == 0x000008, "Wrong alignment on IControllerInterface_C");
static_assert(sizeof(IControllerInterface_C) == 0x000028, "Wrong size on IControllerInterface_C");

}

