#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: menuUIInteraface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "ShopItemCategory_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass menuUIInteraface.menuUIInteraface_C
// 0x0000 (0x0028 - 0x0028)
class ImenuUIInteraface_C final : public IInterface
{
public:
	void Remove();
	void RefreshInventory();
	void RemoveloadoutCategory();
	void ChangeCategory(EShopItemCategory Category);
	void DragItemFromCategory(EShopItemCategory Category);
	void CancelDrag();
	void PreviewItem(class UClass* ItemInfo, int32 SalePrice);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"menuUIInteraface_C">();
	}
	static class ImenuUIInteraface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ImenuUIInteraface_C>();
	}
};
static_assert(alignof(ImenuUIInteraface_C) == 0x000008, "Wrong alignment on ImenuUIInteraface_C");
static_assert(sizeof(ImenuUIInteraface_C) == 0x000028, "Wrong size on ImenuUIInteraface_C");

}

