#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RobberGI

#include "Basic.hpp"

#include "AdvancedSessions_structs.hpp"
#include "SteamCore_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function RobberGI.RobberGI_C.ExecuteUbergraph_RobberGI
// 0x0A08 (0x0A08 - 0x0000)
struct RobberGI_C_ExecuteUbergraph_RobberGI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_StoreStats_ReturnValue;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	class UFriends*                               CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMatchmaking*                           CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FLobbyInviteData& Data)> K2Node_CreateDelegate_OutputDelegate_2;     // 0x003C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const TArray<struct FBPFriendInfo>& Results)> K2Node_CreateDelegate_OutputDelegate_3; // 0x004C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBPFriendInfo>                  K2Node_CustomEvent_Results_3;                      // 0x0060(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FBPFriendInfo>                  K2Node_CustomEvent_Results_2;                      // 0x0070(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FBPFriendInfo>& Results)> K2Node_CreateDelegate_OutputDelegate_4; // 0x0080(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FBPFriendInfo>                  Temp_struct_Variable;                              // 0x0090(0x0010)(ReferenceParm)
	class UInviteRecievedUI_C*                    CallFunc_Create_ReturnValue;                       // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x00AC(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x00BC(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_CC[0x4];                                       // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMessagePopup_C*                        CallFunc_Create_ReturnValue_1;                     // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable;                              // 0x00E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_8;            // 0x0100(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_9;            // 0x0110(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_10;           // 0x0120(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESteamLobbyType                               Temp_byte_Variable;                                // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESteamLobbyType                               Temp_byte_Variable_1;                              // 0x0132(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_133[0x5];                                      // 0x0133(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCreateLobbyData                       K2Node_CustomEvent_Data_1;                         // 0x0138(0x0010)(ConstParm, NoDestructor)
	bool                                          K2Node_CustomEvent_bWasSuccessful;                 // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FCreateLobbyData& Data, bool bWasSuccessful)> K2Node_CreateDelegate_OutputDelegate_11; // 0x014C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15D[0x3];                                      // 0x015D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCreateLobbyData                       Temp_struct_Variable_1;                            // 0x0160(0x0010)(NoDestructor)
	ESteamLobbyType                               Temp_byte_Variable_2;                              // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_1;                            // 0x0178(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_2;                            // 0x0188(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_3;                            // 0x0198(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_4;                            // 0x01A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x01B8(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x01C8(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_14;           // 0x01D8(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_15;           // 0x01E8(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results_1;                      // 0x01F8(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_16; // 0x0208(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FBlueprintSessionResult>        K2Node_CustomEvent_Results;                        // 0x0218(0x0010)(ConstParm, ReferenceParm)
	TDelegate<void(const TArray<struct FBlueprintSessionResult>& Results)> K2Node_CreateDelegate_OutputDelegate_17; // 0x0228(0x0010)(ZeroConstructor, NoDestructor)
	TArray<struct FBlueprintSessionResult>        Temp_struct_Variable_2;                            // 0x0238(0x0010)(ReferenceParm)
	class UServerBrowserUI_C*                     CallFunc_Create_ReturnValue_2;                     // 0x0248(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintSessionResult                CallFunc_Array_Random_OutItem;                     // 0x0258(0x0108)()
	int32                                         CallFunc_Array_Random_OutIndex;                    // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_364[0x4];                                      // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0368(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0378(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x0379(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_37A[0x6];                                      // 0x037A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable_5;                            // 0x0380(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_Map_1;                          // 0x0390(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBlueprintSessionResult                K2Node_CustomEvent_Result;                         // 0x0398(0x0108)()
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UJoinSessionCallbackProxy*              CallFunc_JoinSession_ReturnValue;                  // 0x04A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue;               // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x04B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4BA[0x6];                                      // 0x04BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x04C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_18;           // 0x04C8(0x0010)(ZeroConstructor, NoDestructor)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBPUniqueNetId                         CallFunc_GetUniqueNetID_UniqueNetId;               // 0x04E0(0x0020)()
	int32                                         K2Node_Event_LocalPlayerNum;                       // 0x0500(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_504[0x4];                                      // 0x0504(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPUniqueNetId                         K2Node_Event_PersonInvited;                        // 0x0508(0x0020)()
	struct FBlueprintSessionResult                K2Node_Event_SessionToJoin;                        // 0x0528(0x0108)(ConstParm)
	bool                                          CallFunc_IsPlayerInSession_bIsInSession;           // 0x0630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_631[0x7];                                      // 0x0631(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ACharacter*                             CallFunc_GetPlayerCharacter_ReturnValue;           // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainMenuPlayer_C*                      K2Node_DynamicCast_AsMain_Menu_Player;             // 0x0640(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0648(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_649[0x7];                                      // 0x0649(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULoadingImageUI_C*                      CallFunc_Create_ReturnValue_3;                     // 0x0650(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0658(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_65C[0x4];                                      // 0x065C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPFriendInfo                          CallFunc_Array_Get_Item;                           // 0x0660(0x0068)()
	class FString                                 CallFunc_UniqueNetIdToString_String;               // 0x06C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FLobbyInviteData                       K2Node_CustomEvent_Data;                           // 0x06D8(0x0018)(ConstParm, NoDestructor)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x06F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGetFriendsCallbackProxy*               CallFunc_GetAndStoreFriendsList_ReturnValue;       // 0x06F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_BreakSteamID_ReturnValue;                 // 0x0700(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0710(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0711(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_712[0x6];                                      // 0x0712(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UInviteRecievedUI_C*>            CallFunc_GetAllWidgetsOfClass_FoundWidgets;        // 0x0718(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0728(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_AllowJoinInProgress_;           // 0x072C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x072D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_1;          // 0x072E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_72F[0x1];                                      // 0x072F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue; // 0x0730(0x0020)()
	ESteamLobbyType                               K2Node_Select_Default;                             // 0x0750(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_751[0x7];                                      // 0x0751(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_1; // 0x0758(0x0020)()
	TArray<struct FSessionPropertyKeyPair>        K2Node_MakeArray_Array;                            // 0x0778(0x0010)(ConstParm, ReferenceParm)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_2; // 0x0788(0x0020)()
	class UUpdateSessionCallbackProxyAdvanced*    CallFunc_UpdateSession_ReturnValue;                // 0x07A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_3; // 0x07B0(0x0020)()
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x07D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7D1[0x7];                                      // 0x07D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ALobbyManager_C*                        CallFunc_GetActorOfClass_ReturnValue;              // 0x07D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x07E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E1[0x7];                                      // 0x07E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_CustomEvent_Map;                            // 0x07E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Message;                        // 0x07F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ENetworkFailure                               K2Node_Event_FailureType;                          // 0x0800(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsServer;                            // 0x0801(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0802(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_803[0x5];                                      // 0x0803(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0808(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0818(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_819[0x7];                                      // 0x0819(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_1;                           // 0x0820(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default_2;                           // 0x0830(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_19;           // 0x0840(0x0010)(ZeroConstructor, NoDestructor)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x0850(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue;          // 0x0858(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue_1;             // 0x0868(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_2;          // 0x0870(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0871(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_872[0x6];                                      // 0x0872(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_5;        // 0x0878(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDestroySessionCallbackProxy*           CallFunc_DestroySession_ReturnValue_2;             // 0x0880(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue_1;        // 0x0888(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_3;          // 0x0898(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0899(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_StartSession_ReturnValue;                 // 0x089A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89B[0x5];                                      // 0x089B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSteamID                               CallFunc_GetSteamID_Pure_ReturnValue;              // 0x08A0(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetLobbyType_ReturnValue;                 // 0x08A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8A9[0x7];                                      // 0x08A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_BreakSteamID_ReturnValue_1;               // 0x08B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESteamLobbyType                               K2Node_CustomEvent_LobbyType;                      // 0x08C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C1[0x7];                                      // 0x08C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_4; // 0x08C8(0x0020)()
	class USteamCoreMatchmakingAsyncActionCreateLobby* CallFunc_CreateLobbyAsync_ReturnValue;        // 0x08E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FSessionPropertyKeyPair>        K2Node_MakeArray_Array_1;                          // 0x08F0(0x0010)(ConstParm, ReferenceParm)
	class UCreateSessionCallbackProxyAdvanced*    CallFunc_CreateAdvancedSession_ReturnValue;        // 0x0900(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0908(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0909(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_90A[0x6];                                      // 0x090A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default_3;                           // 0x0910(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetLobbyData_ReturnValue;                 // 0x0920(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_4;          // 0x0921(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetLobbyData_ReturnValue_1;               // 0x0922(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetLobbyJoinable_ReturnValue;             // 0x0923(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_924[0x4];                                      // 0x0924(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_6;        // 0x0928(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCancelFindSessionsCallbackProxy*       CallFunc_CancelFindSessions_ReturnValue;           // 0x0930(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_20;           // 0x0938(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x0948(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_949[0x7];                                      // 0x0949(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_7;        // 0x0950(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCancelFindSessionsCallbackProxy*       CallFunc_CancelFindSessions_ReturnValue_1;         // 0x0958(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSessionPropertyKeyPair                CallFunc_MakeLiteralSessionPropertyString_ReturnValue_5; // 0x0960(0x0020)()
	struct FSessionsSearchSetting                 CallFunc_MakeLiteralSessionSearchProperty_ReturnValue; // 0x0980(0x0028)()
	TArray<struct FSessionsSearchSetting>         K2Node_MakeArray_Array_2;                          // 0x09A8(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x09B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9B9[0x7];                                      // 0x09B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_8;        // 0x09C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFindSessionsCallbackProxyAdvanced*     CallFunc_FindSessionsAdvanced_ReturnValue;         // 0x09C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x09D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9D1[0x3];                                      // 0x09D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_21;           // 0x09D4(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_SetLobbyData_ReturnValue_2;               // 0x09E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_Searching_;                     // 0x09E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9E6[0x2];                                      // 0x09E6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue;            // 0x09E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x09F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetLobbyData_ReturnValue_3;               // 0x09FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x09FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9FE[0x2];                                      // 0x09FE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0A00(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_StoreStats_ReturnValue_1;                 // 0x0A04(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_ExecuteUbergraph_RobberGI;

// Function RobberGI.RobberGI_C.SetSessionSearching
// 0x0001 (0x0001 - 0x0000)
struct RobberGI_C_SetSessionSearching final
{
public:
	bool                                          Searching_;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_SetSessionSearching;

// Function RobberGI.RobberGI_C.CreateSteamLobby
// 0x0001 (0x0001 - 0x0000)
struct RobberGI_C_CreateSteamLobby final
{
public:
	ESteamLobbyType                               LobbyType_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RobberGI_C_CreateSteamLobby;

// Function RobberGI.RobberGI_C.HandleNetworkError
// 0x0002 (0x0002 - 0x0000)
struct RobberGI_C_HandleNetworkError final
{
public:
	ENetworkFailure                               FailureType;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsServer;                                         // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_HandleNetworkError;

// Function RobberGI.RobberGI_C.MessagePopup
// 0x0010 (0x0010 - 0x0000)
struct RobberGI_C_MessagePopup final
{
public:
	class FString                                 Message;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RobberGI_C_MessagePopup;

// Function RobberGI.RobberGI_C.UpdateMap
// 0x0008 (0x0008 - 0x0000)
struct RobberGI_C_UpdateMap final
{
public:
	class UClass*                                 Map_0;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RobberGI_C_UpdateMap;

// Function RobberGI.RobberGI_C.UpdateSession
// 0x0001 (0x0001 - 0x0000)
struct RobberGI_C_UpdateSession final
{
public:
	bool                                          AllowJoinInProgress_;                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_UpdateSession;

// Function RobberGI.RobberGI_C.invited
// 0x0018 (0x0018 - 0x0000)
struct RobberGI_C_invited final
{
public:
	struct FLobbyInviteData                       Data;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_invited;

// Function RobberGI.RobberGI_C.OnSessionInviteAccepted
// 0x0130 (0x0130 - 0x0000)
struct RobberGI_C_OnSessionInviteAccepted final
{
public:
	int32                                         LocalPlayerNum;                                    // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBPUniqueNetId                         PersonInvited;                                     // 0x0008(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FBlueprintSessionResult                SessionToJoin;                                     // 0x0028(0x0108)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_RobberGI_C_OnSessionInviteAccepted;

// Function RobberGI.RobberGI_C.JoinGame
// 0x0108 (0x0108 - 0x0000)
struct RobberGI_C_JoinGame final
{
public:
	struct FBlueprintSessionResult                Result;                                            // 0x0000(0x0108)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_RobberGI_C_JoinGame;

// Function RobberGI.RobberGI_C.HostGame
// 0x0008 (0x0008 - 0x0000)
struct RobberGI_C_HostGame final
{
public:
	class FName                                   Map_0;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RobberGI_C_HostGame;

// Function RobberGI.RobberGI_C.OnSuccess_A110421C4837192EE5791EA86298FC0A
// 0x0010 (0x0010 - 0x0000)
struct RobberGI_C_OnSuccess_A110421C4837192EE5791EA86298FC0A final
{
public:
	TArray<struct FBlueprintSessionResult>        Results_0;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_RobberGI_C_OnSuccess_A110421C4837192EE5791EA86298FC0A;

// Function RobberGI.RobberGI_C.OnFailure_A110421C4837192EE5791EA86298FC0A
// 0x0010 (0x0010 - 0x0000)
struct RobberGI_C_OnFailure_A110421C4837192EE5791EA86298FC0A final
{
public:
	TArray<struct FBlueprintSessionResult>        Results_0;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_RobberGI_C_OnFailure_A110421C4837192EE5791EA86298FC0A;

// Function RobberGI.RobberGI_C.OnCallback_D0E7F30247E9855852002CA389609FEF
// 0x0018 (0x0018 - 0x0000)
struct RobberGI_C_OnCallback_D0E7F30247E9855852002CA389609FEF final
{
public:
	struct FCreateLobbyData                       Data;                                              // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          bWasSuccessful;                                    // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_OnCallback_D0E7F30247E9855852002CA389609FEF;

// Function RobberGI.RobberGI_C.OnSuccess_40CC732343607C4A3B0198893B9834D6
// 0x0010 (0x0010 - 0x0000)
struct RobberGI_C_OnSuccess_40CC732343607C4A3B0198893B9834D6 final
{
public:
	TArray<struct FBPFriendInfo>                  Results_0;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_RobberGI_C_OnSuccess_40CC732343607C4A3B0198893B9834D6;

// Function RobberGI.RobberGI_C.OnFailure_40CC732343607C4A3B0198893B9834D6
// 0x0010 (0x0010 - 0x0000)
struct RobberGI_C_OnFailure_40CC732343607C4A3B0198893B9834D6 final
{
public:
	TArray<struct FBPFriendInfo>                  Results_0;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_RobberGI_C_OnFailure_40CC732343607C4A3B0198893B9834D6;

// Function RobberGI.RobberGI_C.SwitchLobbyType
// 0x0001 (0x0001 - 0x0000)
struct RobberGI_C_SwitchLobbyType final
{
public:
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_SwitchLobbyType;

// Function RobberGI.RobberGI_C.SetLobbyType
// 0x0018 (0x0018 - 0x0000)
struct RobberGI_C_SetLobbyType final
{
public:
	class FString                                 Lobby_type;                                        // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          AllowJoin_;                                        // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_RobberGI_C_SetLobbyType;

}

