#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamInventoryLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SteamInventoryLibrary.SteamInventoryLibrary_C
// 0x0000 (0x0028 - 0x0028)
class USteamInventoryLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static void PurchaseSteamItem(class UClass* BoughtSteamItem, TArray<struct FSteamItemDetails>& Result_items, class UObject* __WorldContext, struct FSteamInventoryResult* Result, bool* Success_);
	static void DoesSteamInventoryContainItem_(class UClass* Inventory_item, TArray<struct FSteamItemDetails>& ResultItems, class UObject* __WorldContext, bool* Return);
	static void GetSteamItemsByCat(const class FString& Item_cat, class UObject* __WorldContext, TArray<struct FSteamItemDetails>* Items, bool* Success_);
	static void GetSteamItemsByID(int32 ID, class UObject* __WorldContext, TArray<struct FSteamItemDetails>* Items, bool* Success_);
	static void UpdateSteamInventoryFromActionResult(const struct FSteamInventoryResult& Result, TArray<struct FSteamItemDetails>& CurrentInventory, class UObject* __WorldContext, TArray<struct FSteamItemDetails>* UpdatedInventory, struct FSteamInventoryResult* Result_out);

	void Get_Steam_Item_Coin_Price(class UClass* Item, class UObject* __WorldContext, int32* Price);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SteamInventoryLibrary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SteamInventoryLibrary_C")
	}
	static class USteamInventoryLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USteamInventoryLibrary_C>();
	}
};
DUMPER7_ASSERTS_USteamInventoryLibrary_C;

}

